SiteConfig:
  extensions:
    - 'SSSEO_SiteConfig_DataExtension'
    
LeftAndMain:
  extensions:
    - 'SSSEO_LeftAndMain_DataExtension'
    
Member:
  extensions:
    - 'SSSEO_Member_DataExtension'
    
SiteTree:
  extensions:
    - 'SSSEO_SiteTree_DataExtension'
